openapi: 3.0.1
info:
  title: Serviços de Titulos
  version: 1.0.0
tags:
  - name: Titulos
    description: Lançamentos de Despesas e Receitas mensal
paths:
  '/titulos/lancamentos/{ano}/{mes}':
    get:
      tags:
        - Titulos
      summary: Serviço para realizar lançamentos de despesas do mes
      operationId: lancamentosTitulo
      parameters:
        - name: ano
          in: path
          required: true
          schema:
            type: integer
        - name: mes
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LancamentosMesResponse'
        '405':
          description: Invalid input
          content: {}
  '/titulos/lancamento/':
    post:
      tags:
        - Titulos
      summary: Serviço para realizar lançamentos de despesas do mes
      operationId: lancamentoTitulo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LancamentoTitulo'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
        '405':
          description: Invalid input
          content: {}
  '/titulos/liquidacao/{id}':
    post:
      tags:
        - Titulos
      summary: Serviço para realizar lançamentos de despesas do mes
      operationId: liquidacaoTitulo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LiquidacaoTitulo'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
        '405':
          description: Invalid input
          content: {}
components:
  schemas:
    LancamentosMesResponse:
      type: object
      properties:
        nmMes:
          type: string
        mes:
          type: integer
        ano:
          type: integer
        valorDespesa:
          type: number
          format: float
        valorReceita:
          type: number
          format: float
        valorSobra:
          type: number
          format: float
        lancamentos:
          type: array
          items:
            type: object
            properties:
              id: 
                type: string
              tipeLancamento:
                type: string
                enum: 
                  - RECEITA
                  - DESPESA
              nmLancamento:
                type: string
              dataVencimento:
                type: string
                format: date
              dataLiquidacao:
                type: string
                format: date
              valorLancamento:
                type: number
                format: float
              valorSaldo:
                type: number
                format: float
              status:
                type: string
                enum: 
                  - PENDENTE
                  - PAGO
                  - ATRASADO
    LancamentoTitulo:
      type: object
      properties:
        id:
          type: string
        descricao:
          type: string
        tipo:
          type: string
        mes:
          type: integer
        ano:
          type: integer
        dataVencimento:
          type: string
          format: date
        dataLiquidacao:
          type: string
          format: date
        valorTitulo:
          type: number
          format: float
        valorPago:
          type: number
          format: float
    LiquidacaoTitulo:
      type: object
      properties:
        dataLiquidacao:
          type: string
          format: date
        valorTitulo:
          type: number
          format: float
        valorPago:
          type: number
